apiVersion: v1
kind: Pod
metadata:
  name: 1stnode
  labels:
    app: store
spec:
  containers:
  - name: 1stnode
    image: nginx
    imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Pod
metadata:
  name: 2ndnode
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - store
        topologyKey: kubernetes.io/hostname
  containers:
  - name: 2ndnode
    image: nginx
    imagePullPolicy: IfNotPresent
